server:
  port: 8081

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: njabulophiri
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false